### ISSUE TITLE
After adding my own firebase file app starts crashing at workoutNow.getDays?

### ISSUE THREAD

**Issue by itinsync-waqarahmad** [vyvital/Fitz#2]

**Comment by vyvital** [comment]
This is because your database on firebase is probably wrong and doesnt fit the scheme of my functions.
Please make your database and adjust the functions accordingly, start with a small DB there is no reason for you to handle the same amount if levels as in my app.
Here is an example of a basic json file that will work

```
{"exercises": [ {
      "id" : 1,
      "name" : "Downword Dog"
    }, {
      "id" : 2,
      "name" : "Warrior Stance"
    } ],
    "id" : 100,
    "name" : "Yoga"
  } ]
```

**Comment by Adnan-addi** [comment]
the above json is invalid to start

**Comment by Adnan-addi** [comment]
kindly give basic correct json in order to work more on the app 
thanks .

**Comment by vyvital** [comment]
The above json is an example of a basic json to start with, this is exactly how part of the DB looks like, the other parts are the User DB and the User Programs DB.
I don't want to sound rude, but it sounds like you just trying to copy paste the entire app without understanding how it works, and the app is 99% available here, the only missing part is the json which you need to build yourself from the documentation I listed in your other issue.

You can start by copying the DB I showed above, and build the correct functions to get the data from the DB, this is exactly 1 line of code.
